#!url=https://vantuan2703/module/deepfaker.module
#!name=DeepFaker💤.mudule
#!desc= By:ѵăռŧυấռ 💤
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/Plugallery.png
#!homepage=https://vantuan2703
#!author=89996462
[Script]
deepfaker=type=http-response,pattern=^https:\/\/api\.deepfaker\.app\/api\/v1\/account\/update-profile,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/deepfaker.js



[MITM]
hostname = %APPEND% api.deepfaker.app
